---
engines:
  sonarcsharp:
    exclude_paths:
      - "**.razor"
      - "src/Logging/Extensions/Log.cs" # Sonar for C# does not understand compile-time logging
  csslint:
    exclude_paths:
      - "**/MainLayout.razor.css"
languages:
  csharp:
    extensions:
      - ".razor"
exclude_paths:
  - "**/.github/**"
  - "**/wwwroot/**"
  - "docs/*.md"
  - "LICENSE.md"
