name: Combined CI / Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - '**'

jobs:
  shared_ci_cd:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    uses: mu88/github-actions/.github/workflows/ci-cd.yml@main
    with:
      github-ref-name: ${{ github.ref }}
      sonar-key: 'mu88_Project28'
      sonar-additional-params: '/d:sonar.cs.opencover.reportsPaths=src/Tests/coverage.opencover.xml /s:$GITHUB_WORKSPACE/SonarQube.Analysis.xml'
      docker-publish-mode: regular_and_chiseled_extra
      docker-publish-project: 'src/WebApp/WebApp.csproj'
      requires-docker-login: true
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  ci_cd:
    runs-on: ubuntu-latest

    needs: shared_ci_cd

    steps:
    - uses: actions/checkout@v5

    - name: Set up .NET
      uses: actions/setup-dotnet@v5

    - name: Build single-file EXE
      run: dotnet publish src/WebApp/WebApp.csproj -r win-x64 -p:PublishSingleFile=true --self-contained true

    - name: Create ZIP for release
      uses: thedoctor0/zip-release@master
      if: ${{ needs.shared_ci_cd.outputs.is-release == 'true' }}
      with:
        type: 'zip'
        filename: ThisIsYourLife.${{ needs.shared_ci_cd.outputs.release-version }}.zip
        directory: 'src/WebApp/bin/Release/net9.0/win-x64/publish'

    - name: Create CHANGELOG
      id: changelog
      uses: Requarks/changelog-action@v1
      if: ${{ needs.shared_ci_cd.outputs.is-release == 'true' }}
      with:
        token: ${{ github.token }}
        tag: ${{ github.ref_name }}
        excludeTypes: build,docs,other,style,chore(deps)

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: ${{ needs.shared_ci_cd.outputs.is-release == 'true' }}
      with:
        files: src/WebApp/bin/Release/net9.0/win-x64/publish/ThisIsYourLife*.zip
        tag_name: ${{ github.ref_name }}
        body: ${{ steps.changelog.outputs.changes }}
