name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
    - name: Restore dependencies
      run: dotnet restore ThisIsYourLife.sln
    - name: Build
      run: dotnet build --no-restore ThisIsYourLife.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ThisIsYourLife.sln
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: registry.hub.docker.com
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Write release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Build Docker and Push
      run: dotnet publish src/WebApp/WebApp.csproj --os linux --arch arm64 /t:PublishContainer '-p:ContainerImageTags="${{ env.VERSION }};latest"' -p:ContainerRegistry=registry.hub.docker.com
    - name: Build single-file EXE
      run: dotnet publish src/WebApp/WebApp.csproj -r win-x64 -p:PublishSingleFile=true --self-contained true
    - name: Create ZIP for release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: ThisIsYourLife.${{ env.VERSION }}.zip
        directory: 'src/WebApp/bin/Release/net8.0/win-x64/publish'
    - name: Create CHANGELOG
      id: changelog
      uses: Requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        tag: ${{ github.ref_name }}
        excludeTypes: build,docs,other,style,chore(deps)
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: src/WebApp/bin/Release/net8.0/win-x64/publish/ThisIsYourLife*.zip
        tag_name: ${{ github.ref_name }}
        body: ${{ steps.changelog.outputs.changes }}